name: 'bien_etre_project'
version: '1.0.0'
config-version: 2 

profile: 'bien_etre_profile'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

models:
  bien_etre_project:
    +materialized: view
    staging:
      +materialized: ephemeral
    marts:
      +materialized: table
