name: bien_etre_project
version: '1.0'

config-version: 2

profile: databricks_profile

model-paths: ["Models"]

models:
  +catalog: workspace_1
  +schema: productivity
  +materialized: table
  +materialization_overrides:
      table:
        version: 2

  bien_etre_project: 
