# dbt_project.yml
name: 'bien_etre_project'
version: '1.0.0'
config-version: 2

profile: 'bien_etre_profile'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

model-paths: ["models"]
data-paths: ["data"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

models:
  bien_etre_project:
    +materialized: view
    staging:
      +materialized: ephemeral
    marts:
      +materialized: table

# packages.yml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1

# models/schema.yml
version: 2

models:
  - name: dim_user
    description: "Informations démographiques de l'utilisateur."
    columns:
      - name: user_id
        description: "ID unique généré pour l'utilisateur."
        tests:
          - not_null
          - unique
      - name: age
        description: "Âge de l'utilisateur."
      - name: gender
        description: "Genre de l'utilisateur."

  - name: dim_job
    description: "Informations liées au type de poste."
    columns:
      - name: job_id
        tests: [not_null, unique]
      - name: job_type
      - name: work_hours_per_day
      - name: breaks_during_work

  - name: dim_platform
    description: "Préférences numériques et usage des réseaux sociaux."
    columns:
      - name: platform_id
        tests: [not_null, unique]

  - name: dim_sommeil
    description: "Habitudes de sommeil."
    columns:
      - name: sommeil_id
        tests: [not_null, unique]

  - name: dim_productivite
    description: "Scores de productivité déclarés et mesurés."
    columns:
      - name: productivite_id
        tests: [not_null, unique]

  - name: dim_sante_mentale
    description: "Indicateurs de bien-être mental."
    columns:
      - name: sante_id
        tests: [not_null, unique]

  - name: fact_bien_etre
    description: "Table de faits centralisant les mesures de bien-être."
    columns:
      - name: user_id
        tests: [not_null]
      - name: job_id
        tests: [not_null]
      - name: platform_id
        tests: [not_null]
      - name: sommeil_id
        tests: [not_null]
      - name: productivite_id
        tests: [not_null]
      - name: sante_id
        tests: [not_null]
      - name: perceived_productivity_score
      - name: actual_productivity_score
      - name: stress_level
      - name: job_satisfaction_score
      - name: days_feeling_burnout_per_month
