name: bien_etre_project
version: '1.0'

config-version: 2

profile: databricks_profile  # ← le nom de ton profile dans ~/.dbt/profiles.yml

model-paths: ["Models"]

models:
  +catalog: workspace_1       # ← appliqué globalement
  +schema: pipeline   # ← sans préfixe automatique
  +materialized: table        # ← tous les modèles seront matérialisés en tables

  bien_etre_project:          # ← ton nom de projet
    # Aucun override nécessaire ici
