SELECT
    {{ dbt_utils.generate_surrogate_key(['age', 'gender', 'uses_focus_apps', 'has_digital_wellbeing_enabled']) }} AS user_id,
    {{ dbt_utils.generate_surrogate_key(['job_type']) }} AS job_id,
    {{ dbt_utils.generate_surrogate_key(['social_platform_preference']) }} AS platform_id,
    {{ dbt_utils.generate_surrogate_key([
        'age',
        'gender',
        'job_type',
        'work_hours_per_day',
        'breaks_during_work',
        'social_platform_preference',
        'daily_social_media_time',
        'number_of_notifications',
        'uses_focus_apps',
        'has_digital_wellbeing_enabled',
        'sleep_hours',
        'screen_time_before_sleep',
        'coffee_consumption_per_day',
        'perceived_productivity_score',
        'actual_productivity_score',
        'stress_level',
        'days_feeling_burnout_per_month',
        'weekly_offline_hours',
        'job_satisfaction_score'
    ]) }} AS fact_id,

    daily_social_media_time,
    number_of_notifications,
    work_hours_per_day,
    perceived_productivity_score,
    actual_productivity_score,
    stress_level,
    sleep_hours,
    screen_time_before_sleep,
    breaks_during_work,
    coffee_consumption_per_day,
    days_feeling_burnout_per_month,
    weekly_offline_hours,
    job_satisfaction_score

FROM {{ source('dbt_productivity', 'productivity') }}
